# ! prof. rule
extra_cfgs:
  skip_proc:
    name: motion_only_block_skip_proc_haze # no_skip_proc, rand_skip_proc
    params:
      scale_factor: 0.5
      block_size_orig: 32
      block_ratio_th: 0.05
      motion:
        name: acc_motion_det.AccMotionDet
        params:
          diff_frame_th: 5
          impact_plus_one: 5
          mask_th: 5
          max_val: 15
          decay: 1
      haze_size_width: 120
      # tau_dark: [0.4, 0.5, 0.6, 0.7, 0.8]
      tau_dark: [0.32, 0.34, 0.36, 0.38, 0.40]