general:
  seed: 1
  outdir: zout/train
  device: cuda
  wandb:
    project: "fire-paper2-2025"
    mode: "online"

dataset:
  available_datasets:
    - "BOOWFire_dataset_chino2015bowfire_splited"
    - "BOWFire_dataset_chino2015bowfire"
    - "DFAN_yar2022optimized"
    - "FD-Dataset_li2020efficient"
    - "TOY_hymenoptera_data"
  splits:
    train:
      dir_name: train
      percent: 0.7
    val:
      dir_name: val
      percent: 0.2
    test:
      dir_name: test
      percent: 0.1
    stratify: true
  export_dir: zout/datasets # in case, auto-splitting is needed (we need to verify this later)
  export_to_disk: true

model:
  pretrained: true

optimizer:
  name: SGD
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0001

training:
  epochs: 30
  batch_size: 32
  gpus: [0]
  num_workers: 4
  checkpoint_interval: 10
  log_interval: 1
  log_best_val: false
  best_model_policy: max_val_acc # "max_val_acc" or "min_val_loss"
  early_stopping:
    patience: 10
    min_delta: 0.001
    monitor: 'val_loss'

infer:
  do_infer: false
  save_results: true
  verbose: false

curriculum_learning:
  enabled: false
  method: "progressive"

fiftyone:
  enabled: false
  force_recreate: true