extra_cfgs:
  result_proc:
    # video: [video_block_skip_rs_proc, fgmask_block_skip_rs_proc]
    video: [video_block_skip_rs_proc]
  skip_proc:
    name: streak_count_proc_eager.StreakCountEagerProc
    params:
      n_chk: 24 # forced check interval (skip state -> eager state transition)
      w_clr: 24 # eager exit window (frames)
      fire_confirm_k: 1 # number of consecutive motion frames to confirm fire state and exit eager state