extra_cfgs:
  video_rs_proc: video_block_skip_rs_proc
  skip_proc:
    name: block_skip_proc # no_skip_proc, rand_skip_proc
    params:
      scale_factor: 1.0
      block_size: 64
      block_active_thresh: 0.1
      motion:
        name: framediff_det.FrameDiffDet
        params:
          diff_thresh: 30
      rule_params:
          active_ratio_threshold: 0.2
          wavelet_channel: r
          wavelet_energy_thres: 50.0