extra_cfgs:
  result_proc:
    # video: [video_block_skip_rs_proc, fgmask_block_skip_rs_proc]
    video: [video_block_skip_rs_proc]
  skip_proc:
    name: window_vote_proc_eager.WindowVoteEagerProc
    params:
      # !Note: valid config <=> fd_win_size >= fd_period
      fd_period: 48 # periodic check interval (frames)
      fd_win_size: 56 # window size for majority voting (frames)