extra_cfgs:
  result_proc:
    # video: [video_block_skip_rs_proc, fgmask_block_skip_rs_proc]
    video: [video_block_skip_rs_proc]
  skip_proc:
    name: pcheck_prof_win_vote_skip_proc_eager.PCheckProfWinVoteSkipProcEager
    params:
      # !Note: valid config <=> fd_win_size >= fd_period
      fd_period: [8, 16, 24, 32] # periodic check interval (frames)
      fd_win_size: [8, 16, 24, 32] # window size for majority voting (frames)