# ! prof. rule
extra_cfgs:
  result_proc:
    video: [video_block_skip_rs_proc, fgmask_block_skip_rs_proc]
  skip_proc:
    name: motion_only_block_skip_proc # no_skip_proc, rand_skip_proc
    params:
      scale_factor: 1.0
       # ! in original frame size (vs block_size: in processed frame size)
      block_size_orig: 32
      block_ratio_th: 0.1
      motion:
        name: framediff_det.FrameDiffDet
        params:
          diff_thresh: 3
