extra_cfgs:
  # diff_thres: 5          # pixel diff threshold for temporal stabilization
  blk_act_thres: 0.05       # % pixels active in block to mark block active
  blk_size: 64             # block size for activity check
  diff_thres: 3 # ! change to default 16 for cv::BackgroundSubtractorMOG2
  firesmoke_cls_thres: 0.1     # fire/smoke classification threshold
  frame_diff_cfg: "config/FrameDifference.xml"
  frm_act_thres: 0.3       # % active blocks to mark frame active
  min_roi: 0.7             # min ROI size (relative to frame) for BIG model
  scale_factor: 1.0      # scale factor for frame diff
  tiny_model: models/tf_mobilenetv3_small_minimal_100.in1k_64x64.pth # tiny CNN model path
  video_rs_handler: FGMaskRSHandler