vars: {
    d2-config: {
      layout-engine: elk
      theme-id: 300
    }
  }
A: |tex
   \displaylines{\text{Input:} \\ \text{FrameBefore } (FB), \\ \text{FrameAfter } (FA), \\ \text{Frame Size } (S)}
| {
    shape: Rectangle
    icon: https://icons.terrastruct.com/essentials%2F012-video%20camera.svg
    icon.near: outside-top-center
}
A.shape: Rectangle

MAIN: {
    direction: right
    label: Main Process
    style.fill: "#f33333"
    style.opacity: 0.5
    style.stroke-dash: 3
    near: center-right

    B: |tex
    \displaylines{\text{Divide } FA \text{ and } FB \\ \text{ into } gs \times gs \text{ grid }}
    |
    B.shape: Rectangle


    C: |tex
        \displaylines{\text{Detect Cell Changes} \\ \text{FrameDiff}}
    |
    C.shape: Rectangle

        # D[Calculate CellDIFF per Cell <br> e.g., mean abs diff]
    D: |tex
        \displaylines{\text{Calculate CellDIFF per Cell} \\ \text{e.g., mean abs diff}}
    |

    D.shape: Rectangle

    E: |tex
        \displaylines{\text{Mark Active Cells If} \\ CellDIFF > \text{Threshold}}
    |

    E.shape: Rectangle

    F: |tex
        \displaylines{\text{Find Bounding Box:} \\ \text{- Wrap Active Cells} \\ \text{- If too few, expand to} \\ \text{minSize of } S, \text{ e.g. } \geq 80\%}
    |

    F.shape: Rectangle
    B --> C --> D --> E --> F
}



H: |tex
   \displaylines{\text{Feed Cropped } FA \\ \text{to Detection Model}}
| {near: bottom-right}
H.shape: Rectangle
A --> MAIN --> H