# pixel diff threshold for temporal stabilization
diff_thres:
  type: list # raw_list or range [start, end, step]
  values: [5]

# scale factor for frame diff
scale_factor:
  type: list
  values: [1, 0.5] 

# block size for activity check
blk_size:
  type: list
  values: [64]

# % pixels active in block to mark block active
blk_act_thres:
  type: range
  values: [0.05, 0.15, 0.05]

# % active blocks to mark frame active and trigger whole frame processing
frm_act_thres:
  type: list
  values: [0.4, 0.7]

# fire/smoke classification threshold
firesmoke_cls_thres:
  type: range
  values: [0.2, 0.51, 0.1]

# min ROI size (relative to frame) for BIG typel
min_roi:
  type: range
  values: [0.5, 0.71, 0.1]