__base__: config/eb0_notemp.yaml

method_cfg:
  list_methods: [] # empty, will populate from config/methods
  selected_method_name: no_temp #temp_tpt #no_temp #temp_stabilize
  tag: "NEW_Model"

dataset_cfg:
  list_datasets: [] # empty, will populate from config/datasets
  selected_dataset_name: Prof
model_cfg:
  base_model: hgnetv2_b5.ssld_stage2_ft_in1k # timm
  model_path: models/prof_NEW_hgnetv2_b5.ssld_stage2_ft_in1k-20250924-9-98.65.pth
  class_names: [Fire, None, SmokeOnly]
  input_size: [360, 640] # [H, W], for timm models

infer_cfg:
  do_infer: true
  skip_if_exists: true
  limit: -1 # -1 for no limit
  save_video_results: false
  save_csv_results: true
  csv_columns:
    - class_names
    - logits
    - probs
    - pred_label_idx
    - pred_label
  calc_metrics: true
  verbose: false