general:
  seed: 1
  # ! Skip if experiment config already exists 
  # ! (existed means: check `Config.expSameCfgExists` in `src/config.py`)
  skip_exp_if_exists: false 
  is_optim_mode: false # Set to true for hyperparameter tuning
  project_dir: null # Auto-resolves to project root
  outdir: zout # Output directory
  computer_name: null # Machine hostname
  time_stamp: null # Auto-populated with current time

dbset_selector:
  list_dbsets: [] # Auto-populated from config/dbsets (the names of yaml files in config/dbsets)
  # ! Target ds: UFireIndoorFull; dev ds: UFireIndoor2
  selected_dbset: UFireIndoor2 
metric_selector:
  list_metrics: [] # Auto-populated from config/metrics
  selected_metric: video_metric # Target evaluation metric
method_selector:
  list_methods: [] # Auto-populated from config/methods
  selected_method: no_temp_method # Selected processing method
modelCfg:
  base_model: hgnetv2_b5.ssld_stage2_ft_in1k # Model architecture name in timm
  model_path: models/__new2_hgnetv2_b5.ssld_stage2_ft_in1k-20260224-76-98.66.pth # Path to model weights
  input_size: [360, 640] # Input resolution [H, W]
  # ! Target classes for prediction
  # ! fire: fire with/without smoke; none: no fire/smoke; smoke: smoke only
  class_names: [fire, none, smoke] # Target prediction classes

inferCfg:
  do_infer: true # Enable inference phase

  # Inference post-processing logic
  infer_proc:
    name: base_infer_proc.NormalInferProc # Selected processing module
    extra: null # Additional parameters for the module

  # Example alternative processing logic
  # infer_proc:
  #   name: base_infer_proc.ProfInferProc
  #   extra:
  #     reliable_th: 0.7 # Confidence threshold for reliable predictions

  num_infer_workers: 0 # Parallel workers (0 for sequential)
  skip_if_exists: true # Skip video if results already exist
  limit: -1 # Max frames to process (-1 for all)
  save_video_results: false # Save visual output as video (.mp4)
  save_csv_results: true # Save numerical output as CSV
  csv_infer_pattern: "_results" # Suffix for CSV filenames
  csv_columns: # Data columns to save in CSV
    - class_names
    - logits
    - probs
    - pred_label_idx
    - pred_label
  calc_metrics: true # Calculate performance metrics
  use_profiler: true # Measure resource usage and execution time
  verbose: false # Enable detailed logging
