__base__: config/__base.yaml

method_cfg:
  list_methods: [] # empty, will populate from config/methods
  selected_method_name: no_temp #temp_tpt #no_temp #temp_stabilize

model_cfg:
  base_model: hgnetv2_b5.ssld_stage2_ft_in1k # timm
  model_path: models/4090_SV__ds_ufire__md_hgnetv2_b5.ssld_stage2_ft_in1k_360x640__ep_50__20250929.211235_best.pth
  class_names: [fire_smoke, None]
  # class_names: [fire_smoke, None, smoke_only]
  input_size: [360, 640] # [H, W], for timm models

infer_cfg:
  do_infer: true
  skip_if_exists: true
  limit: -1 # -1 for no limit
  save_video_results: true
  save_csv_results: true
  csv_columns:
    - class_names
    - logits
    - probs
    - pred_label_idx
    - pred_label
  calc_metrics: true
  verbose: false