general:
  seed: 1
  project_dir: /mnt/e/SyncData/paper2_main
  outdir: zout/zruns
  computer_name: null # PC name that run the experiment
  # time_stamp: 20250729.171542 #  add to outdir automatically, allow to resume training
  time_stamp: null # will be set to current time if not provided
  log_cfg:
    wandb_cfg:
      project: "paper2_main"
      mode: "online"
      wandb_key: 85a60f274011647ab0472ad62fe73da5b1704808

dbset_selector:
  list_dbsets: [] # empty, will populate from config/dbsets
  selected_dbset: UFireIndoor # will be set later

metric_selector:
  list_metrics: [] # empty, will populate from config/metrics
  selected_metric: metric_per_frame # will be set later

method_selector:
  list_methods: [] # empty, will populate from config/methods
  selected_method: noTemp # will be set later

modelCfg:
  base_model: hgnetv2_b5.ssld_stage2_ft_in1k
  model_path: models/_hgnetv2_b5.ssld_stage2_ft_in1k-20251218-93-98.91_2025.12.23.pth
  input_size: [360, 640] # [H, W], for timm models
  class_names: [Fire, None, SmokeOnly]
  # class_names: [FireSmoke, None]

inferCfg:
  do_infer: true
  skip_if_exists: true
  limit: -1 # -1 for no limit
  save_video_results: false
  save_csv_results: true
  csv_columns:
    - class_names
    - logits
    - probs
    - pred_label_idx
    - pred_label
  calc_metrics: true
  log_transforms: true
  verbose: false