dbset:
  type: list # raw_list or range [start, end, step]
  values: ["UFireIndoor"] # ["BowFire", "UFire", "DFAN"]

method:
  type: list
  values: ["temp_method"]
  # values: ["no_temp_method", "temp_baseline_TPT_method", "temp_method"]

metric:
  type: list
  values: ["per_frame_metric"]
