general:
  seed: 1
  skip_exp_if_exists: true # ! skip if same experiment with same config existed
  is_optim_mode: false # ! set to true when doing hyper-parameter optimization
  project_dir: /mnt/e/SyncData/paper2_main
  outdir: zout/zruns
  computer_name: null # PC name that run the experiment
  time_stamp: null
  # time_stamp: 20260212.174219 # 20260209.142136 # null # will be set to current time if not provided
  log_cfg:
    wandb_cfg:
      project: "paper2_main"
      mode: "online"
      wandb_key: 85a60f274011647ab0472ad62fe73da5b1704808
dbset_selector:
  list_dbsets: [] # empty, will populate from config/dbsets
  selected_dbset: UFireIndoorFull # will be set later
metric_selector:
  list_metrics: [] # empty, will populate from config/metrics
  selected_metric: per_frame_metric # will be set later
method_selector:
  list_methods: [] # empty, will populate from config/methods
  selected_method: no_temp_method # noTemp
modelCfg:
  base_model: hgnetv2_b5.ssld_stage2_ft_in1k
  model_path: models/__new2_hgnetv2_b5.ssld_stage2_ft_in1k-20260224-76-98.66.pth
  # base_model: hgnetv2_b6.ssld_stage2_ft_in1k
  # model_path: models/hgnetv2_b6.ssld_stage2_ft_in1k-20260521-9-98.79.pth
  input_size: [360, 640] # [H, W], for timm models
  class_names: [Fire, None, SmokeOnly]
  # class_names: [FireSmoke, None]

inferCfg:
  do_infer: true
  # how model inference results are processed.
  infer_proc:
    name: base_infer_proc.NormalInferProc # ProfInferProc: professor infer logic
    extra: null # extra parameters for the InferProc, if needed
  num_infer_workers: 0 # set to 0 for no parallel; 1 worker for 1 video
  skip_if_exists: true
  limit: -1 # -1 for no limit
  save_video_results: true
  save_csv_results: true
  csv_infer_pattern: "_results"
  csv_columns:
    - class_names
    - logits
    - probs
    - pred_label_idx
    - pred_label
    # ! #TODO: for visualization analysis of eager mode; should disable this if do not want to save this column
    - eager_mode
  calc_metrics: true
  log_transforms: true
  use_profiler: true
  save_timeline_vis:  true
  timeline_table_mode: pfc # options: p (percent), fc (frame count), both (pfc)
  timeline_video_name_limit: 40
  timeline_table_decimals: 4
  verbose: false
