__base__: config/zruns/run_base.yaml
modelCfg:
  base_model: hgnetv2_b5.ssld_stage2_ft_in1k
  model_path: models/__new2_hgnetv2_b5.ssld_stage2_ft_in1k-20260224-76-98.66.pth
  input_size: [360, 640] # [H, W], for timm models
  class_names: [Fire, None, SmokeOnly]
  # class_names: [FireSmoke, None]