vars: {
    d2-config: {
      layout-engine: elk
      theme-id: 300
    }
  }

A: Input
B: use a Fast Background Subtraction Method \n to detect motions
C: use some FAST Optical Flow to \n track the motion
D: test motion have properities of a fire/smoke, \n e.g.: flickering, upward motion
E: extract the ROI of the fire/smoke-like motion
F: feed the ROI to a fire/smoke detection model

A -> B -> C -> D -> E -> F