# ! use the same base config as UFireIndoorFull
__base__: config/dbsets/UFireIndoorFull.yaml

# ! override the dir_path to point to the UFireIndoor2 dataset
# ! Note: UFireIndoor2 is a subset of UFireIndoorFull, containing a much smaller
# ! number of videos, used for quick dev/ testing and debugging.
dir_path: datasets/UFireIndoor2 